### ISSUE TITLE
runAfterInteractions not firing with components in separate files

### ISSUE THREAD

**Issue by zachgibson** [brentvatne/run-after-interactions-exp#1]
I have two components I'm working with. The first, is a preview card and the second is a detailed view of that preview card. Tapping the preview component pushes the detail view on the stack. These components are in separate files and I run InteractionManager in the detailed view. Like so:

```
componentDidMount() {
  InteractionManager.runAfterInteractions(() => {
    console.log('transition complete');
  });
}
```

In this example you have two views and Navigator in the same file, but how would you handle this if “deferAnimations” and “MainScreen” were in one file and “DeferredExpensiveScene” was in another? Maybe this would just work, but for me nothing happens.

Any help or feedback would be dope. Thanks!

**Comment by brentvatne** [comment]
Hi @zachgibson! InteractionManager doesn't care where the code lives :) Can you post the full code that is causing the problem?

Sorry for the slow reply!

**Comment by zachgibson** [comment]
No worries dude! [Here's a gist](https://gist.github.com/zachgibson/7f355166e1ff1569d524) containing the card and card detail view.

**Comment by brentvatne** [comment]
hello! sorry I never got back to you :< I can't see in the InteractionManager code how separation of files could make any difference so closing :(

**Comment by zachgibson** [comment]
Yeah sorry I forgot about his issue. It ended up working later on. 👍  Not sure why tho
