### ISSUE TITLE
Exponent link to demo app doesn't seem to work

### ISSUE THREAD

**Issue by elie222** [brentvatne/run-after-interactions-exp#2]
Trying to visit this on Exponent on my Android isn't working:
`exp://exp.host/@brentvatne/run-after-interactions-example`.

I see the blue ```Something went wrong.``` screen

**Comment by brentvatne** [comment]
oops this is super old, I'll update

**Comment by brentvatne** [comment]
ok fixed and changed link to https://getexponent.com/@community/run-after-interactions-exp
